import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";
import type { EmployeeReport } from "./compute";
import { formatDate } from "../time";

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 10, fontFamily: "Helvetica" },
  header: { fontSize: 14, marginBottom: 4, fontWeight: 700 },
  subheader: { fontSize: 10, color: "#555", marginBottom: 16 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginTop: 12,
    marginBottom: 6,
  },
  table: { display: "flex", flexDirection: "column", marginBottom: 8 },
  row: { flexDirection: "row", borderBottom: 0.5, borderColor: "#ccc" },
  headRow: { flexDirection: "row", borderBottom: 1, borderColor: "#333" },
  cell: { padding: 4, flex: 1 },
  cellNumRight: { padding: 4, flex: 1, textAlign: "right" },
  smallNote: { fontSize: 8, color: "#666", marginTop: 12 },
  totalRow: { flexDirection: "row", borderTop: 1, marginTop: 4 },
  totalLabel: { padding: 4, flex: 1, fontWeight: 700 },
  totalValue: { padding: 4, flex: 1, textAlign: "right", fontWeight: 700 },
});

export function EmployeePdf({
  report,
  periodLabel,
  signatureLine,
}: {
  report: EmployeeReport;
  periodLabel: string;
  signatureLine: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>{report.fullName}</Text>
        <Text style={styles.subheader}>
          Monthly report · {periodLabel} · Portside Logistics
        </Text>

        <Text style={styles.sectionTitle}>Summary</Text>
        <View style={styles.table}>
          <SummaryRow label="Monthly salary (DJF)" value={report.monthlySalary} />
          <SummaryRow
            label="Worked hours"
            value={report.workedHours}
          />
          <SummaryRow
            label="Scheduled hours"
            value={report.scheduledHours}
          />
          <SummaryRow
            label="Late count / total minutes"
            value={`${report.lateCount} / ${report.lateMinutes}`}
          />
          <SummaryRow
            label="Late deduction (DJF)"
            value={report.lateDeductionDjf}
          />
          <SummaryRow
            label="Overtime hours"
            value={report.overtimeHours}
          />
          <SummaryRow
            label="Overtime amount (DJF)"
            value={report.overtimeAmountDjf}
          />
          <SummaryRow
            label="Sick days (certified / uncertified)"
            value={`${report.sickDaysCertified} / ${report.sickDaysUncertified}`}
          />
          <SummaryRow
            label="Vacation / Holiday days"
            value={`${report.vacationDays} / ${report.holidayDays}`}
          />
          <SummaryRow
            label="Unauthorized absence days"
            value={report.unauthAbsenceDays}
          />
          <SummaryRow
            label="Unauthorized absence deduction (DJF)"
            value={report.unauthAbsenceDjf}
          />
          <SummaryRow
            label="Adjustments (DJF)"
            value={report.adjustmentsDjf}
          />
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Net deduction (DJF)</Text>
            <Text style={styles.totalValue}>
              {report.netDeductionDjf.toLocaleString()}
            </Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Net addition (DJF)</Text>
            <Text style={styles.totalValue}>
              {report.netAdditionDjf.toLocaleString()}
            </Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Daily breakdown</Text>
        <View style={styles.table}>
          <View style={styles.headRow}>
            <Text style={styles.cell}>Date</Text>
            <Text style={styles.cellNumRight}>Worked (min)</Text>
            <Text style={styles.cellNumRight}>Late (min)</Text>
            <Text style={styles.cellNumRight}>Early leave (min)</Text>
          </View>
          {report.daily.map((d) => (
            <View key={d.date.toISOString()} style={styles.row}>
              <Text style={styles.cell}>{formatDate(d.date)}</Text>
              <Text style={styles.cellNumRight}>{d.workedMinutes}</Text>
              <Text style={styles.cellNumRight}>{d.lateMinutes}</Text>
              <Text style={styles.cellNumRight}>{d.earlyLeaveMinutes}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.smallNote}>
          Generated by Portside Time. The accountant applies these figures
          externally to produce the actual payroll output.
        </Text>
        <Text style={styles.smallNote}>
          Approved by: {signatureLine}
        </Text>
      </Page>
    </Document>
  );
}

function SummaryRow({
  label,
  value,
}: {
  label: string;
  value: string | number;
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.cell}>{label}</Text>
      <Text style={styles.cellNumRight}>
        {typeof value === "number" ? value.toLocaleString() : value}
      </Text>
    </View>
  );
}

export async function renderEmployeePdf(args: {
  report: EmployeeReport;
  periodLabel: string;
  signatureLine: string;
}): Promise<Buffer> {
  const buf = await pdf(<EmployeePdf {...args} />).toBuffer();
  // @react-pdf's `toBuffer()` returns a `NodeJS.ReadableStream` in some envs and a
  // `Buffer` in others depending on the runtime. Normalize:
  if (Buffer.isBuffer(buf)) return buf;
  return await streamToBuffer(buf as unknown as NodeJS.ReadableStream);
}

async function streamToBuffer(s: NodeJS.ReadableStream): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of s) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  return Buffer.concat(chunks);
}
